# This file can be empty or include imports for ComfyUI to recognize the module
from .nodes.image_preparations import NODE_CLASS_MAPPINGS as IMAGE_PREP_NODE_CLASS_MAPPINGS
from .nodes.image_preparations import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_PREP_DISPLAY_NAME_MAPPINGS
from .nodes.input_image import NODE_CLASS_MAPPINGS as INPUT_IMAGE_NODE_CLASS_MAPPINGS
from .nodes.input_image import NODE_DISPLAY_NAME_MAPPINGS as INPUT_IMAGE_DISPLAY_NAME_MAPPINGS
from .nodes.input_selector import NODE_CLASS_MAPPINGS as INPUT_SELECTOR_NODE_CLASS_MAPPINGS
from .nodes.input_selector import NODE_DISPLAY_NAME_MAPPINGS as INPUT_SELECTOR_DISPLAY_NAME_MAPPINGS

# Combine mappings from all node modules
NODE_CLASS_MAPPINGS = {
    **IMAGE_PREP_NODE_CLASS_MAPPINGS,
    **INPUT_IMAGE_NODE_CLASS_MAPPINGS,
    **INPUT_SELECTOR_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_PREP_DISPLAY_NAME_MAPPINGS,
    **INPUT_IMAGE_DISPLAY_NAME_MAPPINGS,
    **INPUT_SELECTOR_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
